baseURL = 'https://me.kwchang0831.dev/'
languageCode = 'en-us'
title = '@kwchang0831'
theme = 'hugo-theme-shell'
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = 'G-H6FQSD3XNK'

disableKinds = ["taxonomy", "term"]
[taxonomies]
    category = "categories"
    tag = "tags"

[params]
  author = "kwchang0831"
  github = "https://github.com/kwchang0831"
  og_image = "/images/logo.png"
  sitename = "me.kwchang0831.dev"
  description = "My name is AH WEI. Love to try and learn new stuff. Master of none. YOLO! Having fun is all it matters, right?"